# -*- coding: utf-8 -*-
"""mobilenetv2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eenp-WjijQM2iaVRpmBNffJ0qo92W5-i
"""

from tensorflow import keras
from keras.applications import mobilenet_v2

model = keras.applications.MobileNetV2()

!wget https://rukminim1.flixcart.com/image/416/416/hammer/d/m/w/clh-450-taparia-original-imadu93a4f7jnuw5.jpeg?q=70 -O hammer.jpg

import matplotlib.pyplot as plt
from keras.preprocessing import image
z = image.load_img('hammer.jpg',target_size=(224,224,3))
plt.imshow(z)

from keras.applications.mobilenet_v2 import preprocess_input,decode_predictions
z =image.img_to_array(z)
z = z.reshape(1,224,224,3)
z = preprocess_input(z)
y = model.predict(z)
label = decode_predictions(y)
label

for i in range(3):
   print(f'{label[0][i][1]}: {label[0][i][2]*100:.2f}%')